spring:
  datasource:
    url: jdbc:mysql://localhost:3306/etl_db?useSSL=false
    username: etl_user
    password: etl_pass
  jackson:
    date-format: yyyy-MM-dd

etl:
  source:
    paginationSize: 5
  scheduler:
    cron: "0 0 0 * * ?"
  transformConfig: classpath:transform-config.yml
